package rosesefid.com.whiterose;

import android.app.Application;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Typeface;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.preference.PreferenceManager;

import java.util.ArrayList;

import uk.co.chrisjenx.calligraphy.CalligraphyConfig;

//************************************ THE APPLICATION CLASS

public class G extends Application {

    public static String mStr_DateFieldPointer;

    public static Typeface TYPE_FACE_SANS;
    public static Typeface TYPE_FACE_YEKAN;
    public static Context CONTEXT;
    public static String STR_TARGET;

    public static String STR_PACKAGE_NAME;
    public static String STR_HOTEL_NAME;
    public static String STR_DBL;
    public static String STR_SGL;
    public static String STR_BUTTON_NO;
    public static String[] ARRAY_COUNTRY;
    public static String[] ARRAY_CITY_CODE;
    public static String[] ARRAY_CITY;
    public static Boolean DATE_CHANGER = false;
    public static ArrayList sArray_items = new ArrayList();

    public static SharedPreferences SHARED_PREFERENCE_WORLD_CLOCK;
    public static SharedPreferences SHARED_PREFERENCE_FILLER;

    public static String STR_FLIGHT_CHART_DATA;
    public static String STR_PACKAGES;

    //CHECK IF WIFI OR DATA IS CONNECTED
    public static boolean isInternetAvailable() {
        ConnectivityManager conManager = (ConnectivityManager) CONTEXT.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo netInfo = conManager.getActiveNetworkInfo();
        return (netInfo != null && netInfo.isConnected());
    }

    @Override
    public void onCreate() {
        super.onCreate();

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                .setDefaultFontPath("sans.ttf")
                .setFontAttrId(R.attr.fontPath)
                .build()
        );

        SHARED_PREFERENCE_WORLD_CLOCK = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        SHARED_PREFERENCE_FILLER = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());


        //FONTS
        TYPE_FACE_YEKAN = Typeface.createFromAsset(getAssets(), "BYekan.ttf");
        TYPE_FACE_SANS = Typeface.createFromAsset(getAssets(), "sans.ttf");

        CONTEXT = getApplicationContext();

        ARRAY_CITY = new String[]{"تهران",
                "کیش",
                "مشهد",
                "شیراز",
                "اصفهان",
                "استانبول",
                "انتالیا",
                "ازمیر",
                "الانیا",
                "کوالا لامپور",
                "کوش اداسی",
                "بانکوک",
                "پوکت",
                "پاتایا",
                "دهلی",
                "اگرا",
                "جی پور",
                "پکن",
                "شانگهای",
                "هامبورگ",
                "برلین",
                "سیدنی",
                "ملبورن",
                "گلد کوست",
                "کیپ تاون",
                "ژوهانسبورگ",
                "سان سیتی",
                "بروکسل",
                "امستردام",
                "لوزان",
                "رم",
                "پاریس",
                "لندن",
                "دوبی",
                "سنگاپور",
                "باکو",
                "ایروان",
                "تفلیس",
                "گوا",
                "بالی",
                "رباط",
                "تبریز",
                "کرمانشاه",
                "رشت",
                "کرمان",
                "خرم اباد",
                "سنندج",
                "نیشابور",
                "کرج",
                "اهواز",
                "قم",
                "ارومیه",
                "زاهدان",
                "همدان",
                "یزد",
                "قزوین",
                "اردبیل",
                "بندرعباس",
                "بوشهر",
                "بمبئی",
                "کلکته",
                "هانگزو",
                "گوانگجو",
                "بن",
                "فرانکفورت",
                "مونیخ",
                "اشتوتگارت",
                "تونس",
                "دوسلدورف",
                "قاهره",
                "طرابلس",
                "ادیس ابابا",
                "نایروبی",
                "هاوانا",
                "گواتمالا",
                "کاراکاس",
                "سانتیاگو",
                "پاناما",
                "بوینس ایرس",
                "برازیلیا",
                "ریودژانیرو",
                "سائو پائولو",
                "منچستر",
                "نیوکاسل",
                "لیورپول",
                "بلفاست",
                "بیرمنگام",
                "داکا",
                "سارایوو",
                "اسلام اباد",
                "کراچی",
                "پیشاور",
                "لاهور",
                "لیسبون",
                "دوشنبه",
                "عشق اباد",
                "هنگ کنک",
                "پراگ",
                "ماکائو",
                "کپن هاگ",
                "مسکو",
                "سن پترزبورگ",
                "بخارست",
                "توکیو",
                "کیوتو",
                "کلمبو",
                "استکهلم",
                "برن",
                "ژنو",
                "زوریخ",
                "سالزبورگ",
                "خارطوم",
                "دمشق",
                "حلب",
                "موگادیشو",
                "بلگراد",
                "بغداد",
                "اربیل",
                "بصره",
                "کرکوک",
                "موصل",
                "نجف",
                "ریاض",
                "جده",
                "مکه",
                "مدینه",
                "مسقط",
                "قدس",
                "تل اویو",
                "هلسینکی",
                "مانیل",
                "نیکوزیا",
                "دوحه",
                "اوتاوا",
                "تورنتو",
                "کبک",
                "مونترال",
                "ادمونتون",
                "ساسکاتون",
                "سئول",
                "پوسان",
                "پیونگ یانگ",
                "زاگرب",
                "بوگوتا",
                "هاوانا",
                "گوانتانامو",
                "کویت",
                "باتومی",
                "بیروت",
                "ورشو",
                "لوگزامبورگ",
                "بوداپست",
                "اسکندریه",
                "مکزیکوسیتی",
                "موناکو",
                "کاتماندو",
                "اوسلو",
                "واتیکان",
                "کاراکاس",
                "هانوی",
                "روتردام",
                "لاهه",
                "اتن",
                "صنعا",
                "امان",
                "تاشکند",
                "مادرید",
                "بارسلون",
                "والنسیا",
                "کانبرا",
                "اورشلیم",
                "حیفا",
                "براتیسلاوا",
                "کابل",
                "قندهار",
                "مزارشریف",
                "هرات",
                "الجزیره",
                "ابوظبی",
                "شارجه",
                "عجمان",
                "راس الخیمه",
                "جاکارتا",
                "کیف",
                "واشنگتن",
                "دالاس",
                "سانفرانسیسکو",
                "سیاتل",
                "شیکاگو",
                "لس انجلس",
                "میامی",
                "نیویورک",
                "هوستون",
                "اتلانتا",
                "میناپولیس",
                "بوستون",
                "بالتیمور",
                "ساندیگو",
                "پورتلند",
                "دیترویت",
                "ممفیس",
                "دنور",
                "فینیکس",
                "لاس وگاس",
                "هونولولو",
                "فلورانس",
                "میلان",
                "ناپل",
                "ونیز",
                "منامه",
                "دوبلین",
                "ریک یاویک",
                "لهاسا",
                "اولان باتور",
                "ویکتوریا",
                "لیون",
                "مارسی",
                "تولوز",
                "نیس",
                "استراسبورگ",
                "نانسی",
                "کن",
                "کربلا",
                "کاظمین",
                "سامرا",
                "هاوایی",
                "Tehran",
                "Kish",
                "Mashhad",
                "Shiraz",
                "Isfahan",
                "Istanbul",
                "Atlanta",
                "Izmir",
                "Alanya",
                "Kuala Lumpur",
                "Kuşadası",
                "Bangkok",
                "Phuket",
                "Pattaya",
                "Delhi",
                "Agra",
                "Jaipur",
                "Beijing",
                "Shanghai",
                "Hamburg",
                "Berlin",
                "Sydney",
                "Melbourne",
                "Gold Coast",
                "Cape Town",
                "Johannesburg",
                "Sun City",
                "Brussels",
                "Amsterdam",
                "Lausanne",
                "Rome",
                "Paris",
                "london",
                "Dubai",
                "Singapore",
                "Baku",
                "Yerevan",
                "Tbilisi",
                "Goa",
                "Bali",
                "Rabat",
                "Tabriz",
                "kermanshah",
                "rasht",
                "kerman",
                "Khorramabad",
                "Sanandaj",
                "Nishapur",
                "Karaj",
                "Ahvaz",
                "Qom",
                "Urmia",
                "Zahedan",
                "Hamadan",
                "Yazd",
                "Qazvin",
                "Ardabil",
                "Bandar Abbas",
                "Bushire",
                "Mumbai",
                "Kolkata",
                "Hangzhou",
                "Guangzhou",
                "Bonn",
                "Frankfurt",
                "Munich",
                "Stuttgart",
                "Tunis",
                "Dusseldorf",
                "Cairo",
                "Tripoli",
                "Addis Ababa",
                "Nairobi",
                "Havana",
                "Guatemala",
                "Caracas",
                "Santiago",
                "Panama",
                "Buenos Aires",
                "Brasília",
                "Rio de Janeiro",
                "Sao Paulo",
                "Manchester",
                "Newcastle",
                "Liverpool",
                "Belfast",
                "Birmingham",
                "Dhaka",
                "Sarajevo",
                "Islamabad",
                "Karachi",
                "Peshawar",
                "Lahore",
                "Lisbon",
                "Dushanbe",
                "Ashgabat",
                "Hong Kong",
                "Prague",
                "Macau",
                "Copenhagen",
                "Moscow",
                "Saint Petersburg",
                "Bucharest",
                "Tokyo",
                "Kyoto",
                "Colombo",
                "Stockholm",
                "Bern",
                "Geneva",
                "Zurich",
                "Salzburg",
                "Khartoum",
                "Damascus",
                "Aleppo",
                "Mogadishu",
                "Belgrade",
                "Baghdad",
                "Erbil",
                "Basra",
                "Kirkuk",
                "Mosul",
                "Najaf",
                "Riyadh",
                "Jeddah",
                "Mecca",
                "Medina",
                "Muscat",
                "Qods",
                "Tel Aviv",
                "Helsinki",
                "Manila",
                "Nicosia",
                "Doha",
                "Ottawa",
                "Toronto",
                "Quebec",
                "Montreal",
                "Edmonton",
                "Saskatoon",
                "Seoul",
                "Busan",
                "Pyongyang",
                "Zagreb",
                "Bogotá",
                "Havana",
                "Guantanamo",
                "Kuwait",
                "Batumi",
                "Beirut",
                "Warsaw",
                "Luxembourg",
                "Budapest",
                "Alexandria",
                "Mexico City",
                "Monaco",
                "Kathmandu",
                "Oslo",
                "Vatican",
                "Caracas",
                "Hanoi",
                "Rotterdam",
                "Den Haag",
                "Athens",
                "Sana'a",
                "Amman",
                "Tashkent",
                "Madrid",
                "Barcelona",
                "Valencia",
                "Canberra",
                "Jerusalem",
                "Haifa",
                "Bratislava",
                "Kabul",
                "Kandahar",
                "Mazar-i-Sharif",
                "Herat",
                "Algiers",
                "Abu Dhabi",
                "Sharjah",
                "Ajman",
                "Ras al-Khaimah",
                "Jakarta",
                "Kiev",
                "Washington",
                "Dallas",
                "San Francisco",
                "Seattle",
                "Chicago",
                "Los Angeles",
                "Miami",
                "New York",
                "Houston",
                "Atlanta",
                "Minneapolis",
                "Boston",
                "Baltimore",
                "San Diego",
                "Portland",
                "Detroit",
                "Memphis",
                "Denver",
                "Phoenix",
                "Las Vegas",
                "Honolulu",
                "Florence",
                "Milan",
                "Naples",
                "Venice",
                "Manama",
                "Dublin",
                "Reykjavik",
                "Lhasa",
                "Ulaanbaatar",
                "Victoria",
                "Lyon",
                "Marseille",
                "Toulouse",
                "Nice",
                "Strasbourg",
                "Nancy",
                "Cannes",
                "Karbala",
                "Kadhimiya",
                "Samarra",
                "Hawaii"
        };

        ARRAY_CITY_CODE = new String[]{"Asia/Tehran+210841:تهران::Tehran",
                "Asia/Tehran+208797:کیش::Kish",
                "Asia/Tehran+209737:مشهد::Mashhad",
                "Asia/Tehran+208538:شیراز::Shiraz",
                "Asia/Tehran+208194:اصفهان::Isfahan",
                "Asia/Tehran+207308:تبریز::Tabriz",
                "Asia/Tehran+209439:کرمانشاه::kermanshah",
                "Asia/Tehran+208612:رشت::rasht",
                "Asia/Tehran+209375:کرمان::kerman",
                "Asia/Tehran+210291:خرم اباد::Khorramabad",
                "Asia/Tehran+210185:سنندج::Sanandaj",
                "Asia/Tehran+209550:نیشابور::Nishapur",
                "Asia/Tehran+211367:کرج::Karaj",
                "Asia/Tehran+210047:اهواز::Ahvaz",
                "Asia/Tehran+210842:قم::Qom",
                "Asia/Tehran+207147:ارومیه::Urmia",
                "Asia/Tehran+211207:زاهدان::Zahedan",
                "Asia/Tehran+1632085:همدان::Hamadan",
                "Asia/Tehran+211668:یزد::Yazd",
                "Asia/Tehran+210816:قزوین::Qazvin",
                "Asia/Tehran+206976:اردبیل::Ardabil",
                "Asia/Tehran+208929:بندرعباس::Bandar Abbas",
                "Asia/Tehran+207502:بوشهر::Bushire",

                "Asia/Bangkok+318849:بانکوک::Bangkok",
                "Asia/Bangkok+320075:پوکت::Phuket",
                "Asia/Bangkok+317584:پاتایا::Pattaya",

                "Asia/Kolkata+202396:دهلی::Delhi",
                "Asia/Kolkata+206686:اگرا::Agra",
                "Asia/Kolkata+205617:جی پور::Jaipur",
                "Asia/Kolkata+204842:بمبئی::Mumbai",
                "Asia/Kolkata+206690:کلکته::Kolkata",

                "Asia/Shanghai+101924:پکن::Beijing",
                "Asia/Shanghai+106577:شانگهای::Shanghai",
                "Asia/Shanghai+106832:هانگزو::Hangzhou",
                "Asia/Shanghai+102255:گوانگجو::Guangzhou",
                "Asia/Shanghai+61329:لهاسا::Lhasa",

                "Asia/Kuala_Lumpur+233776:کوالا لامپور::Kuala Lumpur",
                "Asia/Dubai+323091:دوبی::Dubai",
                "Asia/Singapore+300597:سنگاپور::Singapore",
                "Asia/Baku+27103:باکو::Baku",
                "Asia/Yerevan+16890:ایروان::Yerevan",
                "Asia/Yerevan+171705:تفلیس::Tbilisi",
                "Asia/Makassar+49512:بالی::Bali",
                "Asia/Dhaka+28143:داکا::Dhaka",

                "Asia/Karachi+258278:اسلام اباد::Islamabad",
                "Asia/Karachi+261158:کراچی::Karachi",
                "Asia/Karachi+259370:پیشاور::Peshawar",
                "Asia/Karachi+260622:لاهور::Lahore",

                "Asia/Dushanbe+313854:دوشنبه::Dushanbe",
                "Asia/Ashgabat+317036:عشق اباد::Ashgabat",
                "Asia/Hong_Kong+1123655:هنگ کنک::Hong Kong",
                "Asia/Macau+60090:ماکائو::Macau",
                "Asia/Colombo+311399:کلمبو::Colombo",
                "Asia/Muscat+258638:مسقط::Muscat",
                "Asia/Manila+264885:مانیل::Manila",
                "Asia/Nicosia+124697:نیکوزیا::Nicosia",
                "Asia/Qatar+271669:دوحه::Doha",
                "Asia/Pyongyang+225058:پیونگ یانگ::Pyongyang",
                "Asia/Kuwait+222056:کویت::Kuwait",
                "Asia/Yerevan+13:باتومی::Batumi",
                "Asia/Beirut+227342:بیروت::Beirut",

                "Asia/Tokyo+226396:توکیو::Tokyo",
                "Asia/Tokyo+725150:کیوتو::Kyoto",

                "Asia/Damascus+314446:دمشق::Damascus",
                "Asia/Damascus+313468:حلب::Aleppo",

                "Asia/Baghdad+207375:بغداد::Baghdad",
                "Asia/Baghdad+206937:اربیل::Erbil",
                "Asia/Baghdad+206820:بصره::Basra",
                "Asia/Baghdad+207046:کرکوک::Kirkuk",
                "Asia/Baghdad+210666:موصل::Mosul",
                "Asia/Baghdad+206905:نجف::Najaf",
                "Asia/Baghdad+209081:کربلا::Karbala",
                "Asia/Baghdad+506871:کاظمین::Kadhimiya",
                "Asia/Baghdad+210875:سامرا::Samarra",

                "Asia/Riyadh+297030:ریاض::Riyadh",
                "Asia/Riyadh+299429:جده::Jeddah",
                "Asia/Riyadh+299427:مکه::Mecca",
                "Asia/Riyadh+296807:مدینه::Medina",

                "Asia/Jerusalem+403327:قدس::Qods",
                "Asia/Jerusalem+215854:تل اویو::Tel Aviv",

                "Asia/Seoul+226081:سئول::Seoul",
                "Asia/Seoul+222888:پوسان::Busan",

                "Asia/Aden+355809:صنعا::Sana'a",
                "Asia/Amman+221790:امان::Amman",
                "Asia/Tashkent+351199:تاشکند::Tashkent",
                "Asia/Katmandu+241809:کاتماندو::Kathmandu",
                "Asia/Jerusalem+213225:اورشلیم::Jerusalem",
                "Asia/Jerusalem+213181:حیفا::Haifa",
                "Asia/Kabul+4361:کابل::Kabul",
                "Asia/Kabul+4366:قندهار::Kandahar",
                "Asia/Kabul+2244:مزارشریف::Mazar-i-Sharif",
                "Asia/Kabul+4013:هرات::Herat",
                "Asia/Dubai+321626:ابوظبی::Abu Dhabi",
                "Asia/Dubai+321623:شارجه::Sharjah",
                "Asia/Dubai+1939:عجمان::Ajman",
                "Asia/Dubai+325529:راس الخیمه::Ras al-Khaimah",
                "Asia/Jakarta+20897:جاکارتا::Jakarta",
                "Asia/Bahrain+29687:منامه::Manama",
                "Asia/Ulaanbaatar+246421:اولان باتور::Ulaanbaatar",

                "Europe/Istanbul+318251:استانبول::Istanbul",
                "Europe/Istanbul+316939:انتالیا::Atlanta",
                "Europe/Istanbul+318290:ازمیر::Izmir",
                "Europe/Istanbul+316940:الانیا::Alanya",
                "Europe/Istanbul+317049:کوش اداسی::Kuşadası",

                "Europe/Berlin+178556:هامبورگ::Hamburg",
                "Europe/Berlin+178087:برلین::Berlin",
                "Europe/Berlin+170369:بن::Bonn",
                "Europe/Berlin+168720:فرانکفورت::Frankfurt",
                "Europe/Berlin+178086:مونیخ::Munich",
                "Europe/Berlin+167220:اشتوتگارت::Stuttgart",
                "Europe/Berlin+170372:دوسلدورف::Dusseldorf",

                "Europe/Brussels+27581:بروکسل::Brussels",
                "Europe/Amsterdam+249758:امستردام::Amsterdam",
                "Europe/Zurich+316303:لوزان::Lausanne",

                "Europe/Rome+213490:رم::Rome",
                "Europe/Rome+216189:فلورانس::Florence",
                "Europe/Rome+214046:میلان::Milan",
                "Europe/Rome+212466:ناپل::Naples",
                "Europe/Rome+216711:ونیز::Venice",

                "Europe/Paris+623:پاریس::Paris",
                "Europe/Paris+171210:لیون::Lyon",
                "Europe/Paris+170960:مارسی::Marseille",
                "Europe/Paris+135244:تولوز::Toulouse",
                "Europe/Paris+136420:نیس::Nice",
                "Europe/Paris+131836:استراسبورگ::Strasbourg",
                "Europe/Paris+135030:نانسی::Nancy",
                "Europe/Paris+136419:کن::Cannes",

                "Europe/London+328328:لندن::london",
                "Europe/London+329260:منچستر::Manchester",
                "Europe/London+329683:نیوکاسل::Newcastle",
                "Europe/London+330510:لیورپول::Liverpool",
                "Europe/London+326960:بیرمنگام::Birmingham",

                "Europe/Belfast+326934:بلفاست::Belfast",
                "Europe/Sarajevo+33028:سارایوو::Sarajevo",

                "Europe/Lisbon+274087:لیسبون::Lisbon",
                "Europe/Prague+125594:پراگ::Prague",
                "Europe/Copenhagen+123094:کپن هاگ::Copenhagen",
                "Europe/Moscow+294021:مسکو::Moscow",
                "Europe/Moscow+295212:سن پترزبورگ::Saint Petersburg",

                "Europe/Bucharest+287430:بخارست::Bucharest",
                "Europe/Stockholm+314929:استکهلم::Stockholm",
                "Europe/Zurich+312122:برن::Bern",
                "Europe/Zurich+313082:ژنو::Geneva",
                "Europe/Zurich+316622:زوریخ::Zurich",
                "Europe/Vienna+30760:سالزبورگ::Salzburg",
                "Europe/Belgrade+298198:بلگراد::Belgrade",
                "Europe/Helsinki+133328:هلسینکی::Helsinki",
                "Europe/Zagreb+117910:زاگرب::Zagreb",
                "Europe/Warsaw+274663:ورشو::Warsaw",
                "Europe/Luxembourg+228714:لوگزامبورگ::Luxembourg",
                "Europe/Budapest+187423:بوداپست::Budapest",
                "Europe/Monaco+5174:موناکو::Monaco",
                "Europe/Oslo+254946:اوسلو::Oslo",
                "Europe/Vatican+2216947:واتیکان::Vatican",
                "Europe/Amsterdom+251688:روتردام::Rotterdam",
                "Europe/Amsterdom+1148994:لاهه::Den Haag",
                "Europe/Athens+182536:اتن::Athens",
                "Europe/Madrid+308526:مادرید::Madrid",
                "Europe/Madrid+307297:بارسلون::Barcelona",
                "Europe/Madrid+352579:والنسیا::Valencia",
                "Europe/Bratislava+297345:براتیسلاوا::Bratislava",
                "Europe/Kiev+324505:کیف::Kiev",
                "Europe/Dublin+207931:دوبلین::Dublin",

                "Australia/Sydney+22889:سیدنی::Sydney",
                "Australia/Melbourne+26216:ملبورن::Melbourne",
                "Australia/Brisbane+13978:گلد کوست::Gold Coast",

                "Africa/Johannesburg+306633:کیپ تاون::Cape Town",
                "Africa/Johannesburg+305448:ژوهانسبورگ::Johannesburg",
                "Africa/Johannesburg+336872:سان سیتی::Sun City",

                "Africa/Casablanca+245072:رباط::Rabat",
                "Africa/Tunis+321398:تونس::Tunis",
                "Africa/Cairo+127164:قاهره::Cairo",
                "Africa/Tripoli+230555:طرابلس::Tripoli",
                "Africa/Addis_Ababa+126831:ادیس ابابا::Addis Ababa",
                "Africa/Nairobi+224758:نایروبی::Nairobi",
                "Africa/Khartoum+308406:خارطوم::Khartoum",
                "Africa/Mogadisho+297120:موگادیشو::Mogadishu",
                "Africa/Cairo+126995:اسکندریه::Alexandria",

                "America/Havana+122438:هاوانا::Havana",
                "America/Guatemala+168476:گواتمالا::Guatemala",
                "America/Caracas+353020:کاراکاس::Caracas",
                "America/Santiago+60449:سانتیاگو::Santiago",
                "America/Panama+107784:پاناما::Panama",
                "America/Argentina/Buenos_Aires+7894:بوینس ایرس::Buenos Aires",

                "America/Sao_Paulo+43348:برازیلیا::Brasília",
                "America/Sao_Paulo+45449:ریودژانیرو::Rio de Janeiro",
                "America/Sao_Paulo+45881:سائو پائولو::Sao Paulo",

                "America/Toronto+55487:اوتاوا::Ottawa",
                "America/Toronto+55488:تورنتو::Toronto",
                "America/Toronto+50011:کبک::Quebec",
                "America/Toronto+56186:مونترال::Montreal",
                "America/Edmonton+52478:ادمونتون::Edmonton",
                "America/Winnipeg+50338:ساسکاتون::Saskatoon",

                "America/Bogota+107487:بوگوتا::Bogotá",
                "America/Mexico_City+242560:مکزیکوسیتی::Mexico City",

                "America/New_York+327659:واشنگتن::Washington",
                "America/New_York+347936:میامی::Miami",
                "America/New_York+349727:نیویورک::New York",
                "America/New_York+348181:اتلانتا::Atlanta",
                "America/New_York+348735:بوستون::Boston",
                "America/New_York+348707:بالتیمور::Baltimore",
                "America/New_York+348755:دیترویت::Detroit",

                "America/Chicago+351194:دالاس::Dallas",
                "America/Chicago+348308:شیکاگو::Chicago",
                "America/Chicago+351197:هوستون::Houston",
                "America/Chicago+348794:میناپولیس::Minneapolis",
                "America/Chicago+351089:ممفیس::Memphis",

                "America/Los_Angeles+347629:سانفرانسیسکو::San Francisco",
                "America/Los_Angeles+351409:سیاتل::Seattle",
                "America/Los_Angeles+347625:لس انجلس::Los Angeles",
                "America/Los_Angeles+347828:ساندیگو::San Diego",
                "America/Los_Angeles+350473:پورتلند::Portland",
                "America/Los_Angeles+329506:لاس وگاس::Las Vegas",

                "America/Denver+347810:دنور::Denver",
                "America/Denver+346935:فینیکس::Phoenix",
                "America/Honolulu+348211:هونولولو::Honolulu",
                "America/Vancouver+47163:ویکتوریا::Victoria",

                "Cuba+122794:گوانتانامو::Guantanamo",
                "Asia/Kolkata+262590:گوا::Goa",
                "Asia/Ho_Chi_Minh+353412:هانوی::Hanoi",

                "Atlantic/Reykjavik+190390:ریک یاویک::Reykjavik",
                "Australia/Canberra+21921:کانبرا::Canberra",
                "Africa/Algiers+2093:الجزیره::Algiers",

                "US/Hawaii+1168097:هاوای::Hawaii"
        };

        ARRAY_COUNTRY = new String[]{"0:1/Germany_آلمان",
                "0:2/Switzerland_سوییس",
                "0:3/Norway_نروژ",
                "21:0/Vietnam_ویتنام",
                "0:4/Austria_اتریش",
                "96:5/Ethiopia_اتیوپی",
                "121:6/Jordan_اردن",
                "40:7/Armenia_ادمنستان",
                "115:8/Eritrea_اریتره",
                "41:9/Uzbekistan_ازبکستان",
                "0:10/Spain_اسپانیا",
                "0:11/Australia_استرالیا",
                "0:12/Estonia_استونی",
                "110:13/Scotland_اسکاتلند",
                "0:14/Slovakia_اسلواکی",
                "45:15/Slovenia_اسلوونی",
                "109:16/Afghanistan_افغانستان",
                "120:17/Ecuador_اکوادور",
                "106:18/Algeria_الجزیره",
                "0:19/El Salvador_السالوادور",
                "22:20/UnitedArabEmirates_امارات متحده عربی",
                "47:21/Indonesia_اندونزی",
                "0:22/England_انگلستان",
                "130:23/Uruguay_اروگوئه",
                "135:24/Ukraine_اوکراین",
                "0:25/Uganda_اوگاندا",
                "0:26/Iran_ایران",
                "103:27/Ireland_ایرلند",
                "0:28/Italy_ایتالیا",
                "0:29/Iceland_ایسلند",
                "36:30/Argentina_آرژانتین",
                "37:31/South Africa_آفریقای جنوبی",
                "38:32/Central African Republic_آفریقای مرکزی",
                "101:33/Albania_آلبانی",
                "0:34/United States_ایالات متحده",
                "0:35/Antigua and Barbuda_آنتیگوا و باربودا",
                "0:36/Andorra_آندورا",
                "0:37/Angola_آنگولا",
                "0:38/Barbados_باربادوس",
                "0:39/Bahamas_باهاما",
                "31:40/Bahrain_بحرین",
                "48:41/Brazil_برزیل",
                "0:42/Brunei_برونئی",
                "0:43/United Kingdom_بریتانیا",
                "117:44/Belarus_بلاروس",
                "0:45/Belgium_بلژیک",
                "50:46/Bulgaria_بلغارستان",
                "0:47/Belize_بلیز",
                "11:48/Bangladesh_بنگلادش",
                "0:49/Benin_بنین",
                "0:50/Bhutan_بوتان",
                "0:51/Botswana_بوتسوانا",
                "0:52/Burkina Faso_بورکینافاسو",
                "0:53/Burundi_بروندی",
                "104:54/Bosna i Hercegovina_بوسنی و هرزگوین",
                "151:55/Bolivia_بولیوی",
                "0:56/Papua New Guinea_گینه نو",
                "52:57/Paraguay_پاراگوئه",
                "53:58/Pakistan_پاکستان",
                "107:59/Panama_پاناما",
                "0:60/Portugal_پرتقال",
                "148:61/Peru_پرو",
                "55:62/Tajikistan_تاجیکستان",
                "136:63/Tanzania_تانزانیا",
                "56:64/Thailand_تایلند",
                "0:65/Taiwan_تایوان",
                "57:66/Turkmenistan_ترکمنستان",
                "5:67/Turkey_ترکیه",
                "0:68/Trinidad and Tobago_ترینیداد و توباگو",
                "0:69/Togo_توگو",
                "119:70/Tunisia_تونس",
                "0:71/Tonga_تونگا",
                "0:72/Tuvalu_توالو",
                "0:73/Jamaica_جامیکا",
                "0:74/Solomon Islands_جزایر سولومون",
                "0:75/Czech Republic_جمهوری چک",
                "0:76/Djibouti_جیبوتی",
                "0:77/Chad_چاد",
                "59:78/China_چین",
                "0:79/Denmark_دانمارک",
                "0:80/Dominican_دومینیکن",
                "0:81/Dominica_دومینیکا",
                "0:82/Rwanda_رواندا",
                "12:83/Russia_روسیه",
                "61:84/Romania_رومانی",
                "0:85/Zambia_زامبیا",
                "0:86/zelandeno_زلاندنو",
                "129:87/Zimbabwe_زیمباوه",
                "145:88/Congo_کونگو",
                "15:89/Japan_ژاپن",
                "0:90/Cote d'Ivoire_ساحل عاج",
                "0:91/Samoa_ساموا",
                "0:92/San Marino_سن ماریو",
                "0:93/Sao Tome and Principe_سائوتومه و پرینسیپ",
                "64:94/Seri Lanka_سریلانکا",
                "0:95/Saint Kitts and Nevis_سنت کیتس و نویس",
                "0:96/Saint Lucia_سنت لوکا",
                "0:97/Saint Vincent and the Grenadines_سنت وینسنت و گرنادینها",
                "65:98/Singapore_سنگاپور",
                "141:99/Senegal_سنگال",
                "0:100/Swaziland_سوازیلند",
                "67:101/Sudan_سودان",
                "0:102/Suriname_سورینام",
                "68:103/Syria_سوریه",
                "69:104/Somalia_سومالی",
                "0:105/Sweden_سوئد",
                "70:106/Sierra Leone_سیرالئون",
                "0:107/Seychelles_سیشل",
                "124:108/Chile_شیلی",
                "122:109/serbestan_صربستان",
                "0:110/Montenegro_مونتنگرو",
                "71:111/Iraq_عراق",
                "72:112/Saudi Arabia_عربستان سعودی",
                "73:113/Oman_عمان",
                "138:114/Ghana_غنا",
                "0:115/France_فرانسه",
                "0:116/Phalestine_فلسطین",
                "0:117/Finland_فنلاند",
                "0:118/Fiji_فیجی",
                "76:119/Philippines_فیلیپین",
                "77:120/Cyprus_قبرس",
                "78:121/Kyrgyzstan_قرقیزستان",
                "78:122/Kazakhstan_قزاقستان",
                "58:0/Azerbaijan_آذربایجان",
                "80:123/Qatar_قطر",
                "0:124/Costa Rica_کاستاریکا",
                "81:125/Cambodia_کامبوج",
                "0:126/Cameroon_کامرون",
                "0:127/Canada_کانادا",
                "14:128/Korea South_کره جنوبی",
                "83:129/KoreaNorth_کره شمالی",
                "82:130/Croatia_کرواسی",
                "105:131/Colombia_کلمبیا",
                "111:132/Kenya_کنیا",
                "84:133/Cuba_کوبا",
                "85:134/Kuwait_کویت",
                "0:135/Cape Verde_کیپ ورد",
                "0:136/Kiribati_کیریباتی",
                "0:137/Gabon_گابن",
                "0:138/Gambia_گامبیا",
                "0:139/Grenada_گرانادا",
                "29:140/Georgia_گرجستان",
                "0:141/Guatemala_گواتمالا",
                "0:142/Guyana_گویان",
                "142:143/Guinea_گینه",
                "0:144/Equatorial Guinea_گینه استوایی",
                "0:145/Guinea-Bissau_گینه بیسائو",
                "144:146/Laos_لائوس",
                "6:147/Lebanon_لبنان",
                "0:148/Latvia_لتونی",
                "0:149/Lesotho_لسوتو",
                "0:150/Poland_لهستان",
                "0:151/Logzambourg_لگزامبورگ",
                "0:152/Liberia_لیبریا",
                "98:153/Libya_لیبی",
                "0:154/Liechtenstein_لیختن اشتاین",
                "0:155/Lithuania_لیتوانی",
                "143:156/Madagascar_ماداگاسکار",
                "0:157/Malawi_مالاوی",
                "0:158/Malta_مالت",
                "152:159/Maldives_مالدیو",
                "30:160/Malaysia_مالزی",
                "108:161/Mali_مالی",
                "0:162/Hungary_مجارستان",
                "0:163/Union of the Comoros_اتحادیه کومور",
                "27:164/Egypt_مصر",
                "140:165/Morocco_مراکش",
                "0:166/Mongolia_مغولستان",
                "0:167/Macedonia_مقدونیه",
                "88:168/Mexico_مکزیک",
                "0:169/Mauritania_موریتانی",
                "0:170/Mauritius_موریس",
                "0:171/Mozambique_موزامبیک",
                "126:172/Moldova_مولدووا",
                "0:173/Monaco_موناکو",
                "49:174/Myanmar_میانمار",
                "0:175/Micronesia_میکرونزی",
                "0:176/Namibia_نامبیا",
                "0:177/Nauru_نائورو",
                "0:178/Nepal_نپال",
                "0:179/Niger_نیجر",
                "112:180/Nigeria_نیجریه",
                "0:181/Nicaragua_نیکاراگوئه",
                "0:182/New Zealand_نیوزیلند",
                "0:183/Haiti_هائیتی",
                "0:184/Netherlands_هلند",
                "0:185/Honduras_هندوراس",
                "0:186/Vatican City_شهر واتیکان",
                "0:187/Vanuatu_وانواتو",
                "116:188/Venezuela_ونزوئلا",
                "86:189/Yemen_یمن",
                "0:190/Greek_یونان",
                "16:191/India_هند"};
    }
}
